markdown:         redcarpet
highlighter:      pygments

title: davison online
email: darren@davisononline.org
description: a home for things that had no better place to be.
url: https://davison.github.io/

# Build settings
#markdown: kramdown
paginate: 5

github: [metadata]

author:
  work: https://linkedin.com/in/davisononline
  git: davison
  