title: davison online
email: darren@davisononline.org
description: a home for things that had no better place to be.
url: https://davison.github.io

# Build settings
paginate: 10
related:
  max-posts: 5
  min-common-tags: 2

github: [metadata]

author:
  work: https://linkedin.com/in/davisononline
  git: davison
  
plugins:
  - jekyll-sitemap
  