name: Build site

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install zensical
      - run: python3 main.py
      - run: zensical build --clean
